import type { CSSProperties } from "react";
import { POPOVER_MAX_HEIGHT, POPOVER_WIDTH } from "./constants";

export const s = {
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    cursor: "help",
    borderRadius: 4,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  chip: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    paddingBottom: 1,
    fontSize: 13,
    fontWeight: 600,
    color,
    borderBottom: `1px dotted ${color}`,
  }),
  /** `pos` is null until the first measurement — rendered hidden to measure it. */
  popover: (pos: { top: number; left: number; maxHeight: number } | null): CSSProperties => ({
    position: "fixed",
    top: pos?.top ?? 0,
    left: pos?.left ?? 0,
    zIndex: 1000,
    width: POPOVER_WIDTH,
    maxWidth: "calc(100vw - 16px)",
    maxHeight: pos?.maxHeight ?? POPOVER_MAX_HEIGHT,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "12px 16px 4px",
    borderRadius: 10,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    boxShadow: "var(--shadow-modal)",
    cursor: "default",
    textAlign: "left",
    whiteSpace: "normal",
    visibility: pos ? "visible" : "hidden",
  }),
  header: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    marginBottom: 4,
    fontSize: 11.5,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  item: (first: boolean): CSSProperties => ({
    padding: "12px 0",
    borderTop: first ? "none" : "1px solid var(--border)",
  }),
  // Inline flow, not flex: a long title wraps beside the badge and the
  // category tag drops to the next line, as in the design.
  titleRow: { lineHeight: 1.7 } satisfies CSSProperties,
  badgeSlot: {
    display: "inline-flex",
    verticalAlign: "middle",
    marginRight: 10,
  } satisfies CSSProperties,
  title: (dismissed: boolean): CSSProperties => ({
    fontSize: 13.5,
    fontWeight: 600,
    verticalAlign: "middle",
    color: dismissed ? "var(--text-muted)" : "var(--text-primary)",
    textDecoration: dismissed ? "line-through" : "none",
  }),
  categorySlot: {
    display: "inline-flex",
    verticalAlign: "middle",
    marginLeft: 10,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "2px 12px",
    marginTop: 4,
  } satisfies CSSProperties,
  fileLink: {
    minWidth: 0,
    fontSize: 12.5,
    color: "var(--accent-text)",
    textDecoration: "none",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  confidence: { flexShrink: 0 } satisfies CSSProperties,
  rationale: {
    marginTop: 6,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  status: {
    padding: "8px 0 12px",
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "8px 0 12px",
  } satisfies CSSProperties,
} as const;
