import type { CSSProperties } from "react";

export const s = {
  root: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    marginBottom: 14,
    overflow: "hidden",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", paddingRight: 12 } satisfies CSSProperties,
  toggle: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "13px 4px 13px 16px",
    cursor: "pointer",
    color: "var(--text-primary)",
    background: "none",
    border: "none",
    font: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  mutedIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  agentName: { fontWeight: 600, fontSize: 14 } satisfies CSSProperties,
  counts: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  cost: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  when: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
    color: "var(--text-muted)",
  }),
  deleteBtn: (pending: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    cursor: pending ? "not-allowed" : "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    padding: 4,
  }),
  spinning: { animation: "ddspin 1s linear infinite" } satisfies CSSProperties,
  body: { padding: "0 16px 16px" } satisfies CSSProperties,
  banner: { marginBottom: 16 } satisfies CSSProperties,
};
